import { Router } from "express";
import { publicRouter } from "./public/routes.js";
import { authAdminRouter } from "./auth/routes.js";
import { adminManagementRouter } from "./admin-management/routes.js";
import { adminDashboardRouter } from "./admin-dashboard/routes.js";
import { licenseVerificationRouter } from "./license-verification/routes.js";
import { userManagementRouter } from "./user-management/routes.js";
import { pharmacyManagementRouter } from "./pharmacy-management/routes.js";
import { driverManagementRouter } from "./driver-management/routes.js";
import { diseaseAlertRouter } from "./disease-alerts/routes.js";
import { analyticsRouter } from "./analytics/routes.js";
import { reportsRouter } from "./analytics/reports.js";
import { auditLogRouter } from "./audit-logs/routes.js";
import { orderManagementRouter } from "./order-management/routes.js";
import { deliveryManagementRouter } from "./delivery-management/routes.js";
import { complaintManagementRouter } from "./complaint-management/routes.js";
import { paymentManagementRouter } from "./payment-management/routes.js";
import { platformSettingsRouter } from "./platform-settings/routes.js";

export const adminRouter = Router();

adminRouter.use("/public", publicRouter);
adminRouter.use("/auth", authAdminRouter);
adminRouter.use("/admins", adminManagementRouter);
adminRouter.use("/", adminDashboardRouter);
adminRouter.use("/licenses", licenseVerificationRouter);
adminRouter.use("/verifications", licenseVerificationRouter);
adminRouter.use("/users", userManagementRouter);
adminRouter.use("/pharmacies", pharmacyManagementRouter);
adminRouter.use("/drivers", driverManagementRouter);
adminRouter.use("/alerts", diseaseAlertRouter);
adminRouter.use("/analytics", analyticsRouter);
adminRouter.use("/reports", reportsRouter);
adminRouter.use("/audit-logs", auditLogRouter);
adminRouter.use("/orders", orderManagementRouter);
adminRouter.use("/deliveries", deliveryManagementRouter);
adminRouter.use("/complaints", complaintManagementRouter);
adminRouter.use("/payments", paymentManagementRouter);
adminRouter.use("/platform-settings", platformSettingsRouter);
